# Core SDK settings
AE_MAIN_KEY: "Yg&tc%DEuh6%Zc^8"
AE_MAIN_IV: "6oyZDr22E3ychjM%"

HEADERS_COMMON_USER_AGENT: "Dalvik/2.1.0 (Linux; U; Android 13; A063 Build/TKQ1.221220.001)"
HEADERS_COMMON_CONNECTION: "Keep-Alive"
HEADERS_COMMON_ACCEPT_ENCODING: "gzip"
HEADERS_COMMON_EXPECT: "100-continue"
HEADERS_COMMON_X_UNITY_VERSION: "2018.4.11f1"
HEADERS_COMMON_X_GA: "v1 1"
HEADERS_COMMON_RELEASE_VERSION: "OB53"
HEADERS_COMMON_CONTENT_TYPE: "application/x-www-form-urlencoded"

HEADERS_GARENA_AUTH_USER_AGENT: "GarenaMSDK/4.0.19P9(A063 ;Android 13;en;IN;)"
HEADERS_GARENA_AUTH_CONNECTION: "Keep-Alive"
HEADERS_GARENA_AUTH_ACCEPT_ENCODING: "gzip"

URL_GARENA_GUEST_REGISTER: "https://100067.connect.garena.com/api/v2/oauth/guest:register"
URL_GARENA_TOKEN: "https://100067.connect.garena.com/api/v2/oauth/guest/token:grant"
URL_LOGIN_BASE: "https://loginbp.ggpolarbear.com"
URL_MAJOR_LOGIN: "https://loginbp.ggpolarbear.com/MajorLogin"
URL_PATH_SEARCH: "/FuzzySearchAccountByName"
URL_PATH_PERSONAL_SHOW: "/GetPlayerPersonalShow"
URL_PATH_PLAYER_STATS: "/GetPlayerStats"
URL_PATH_PLAYER_CS_STATS: "/GetPlayerTCStats"
URL_PATH_RECOMMENDED_FRIEND: "/GetRecommendedFriend"
URL_PATH_ACCOUNT_OUTFIT: "/GetAccountOutfit"
URL_PATH_PLAYER_GALLERY_SHOW_INFO: "/GetPlayerGalleryShowInfo"
URL_PATH_VISITORS: "/GetVisitors"
URL_PATH_INTERACTION_RECORD: "/GetInteractionRecord"
URL_PATH_ACCOUNT_ACHIEVEMENT_INFO: "/GetAccountAchievementInfo"
URL_PATH_WORKSHOP_AUTHOR_INFO: "/GetWorkshopAuthorInfo"
URL_PATH_SPECIAL_FRIEND_LIST: "/GetSpecialFriendList"
URL_PATH_PLAYER_CS_RANKING_INFO_BY_ACCOUNT_ID: "/GetPlayerCSRankingInfoByAccountID"
URL_PATH_OCCUPATION_INFO: "/GetOccupationInfo"

GARENA_CLIENT_ID: "100067"
GARENA_CLIENT_SECRET: "2ee44819e9b4598845141067b281621874d0d5d7af9d8f7e00c1e54715b7d1e3"
