import protobuf from 'protobufjs';
export async function loadProtobufRoot(): Promise<protobuf.Root> {
  const root = new protobuf.Root();
  const FreeFire = new protobuf.Namespace('FreeFire');
  const LoginReq = new protobuf.Type('LoginReq');
  LoginReq.add(new protobuf.Field('open_id', 22, 'string'));
  LoginReq.add(new protobuf.Field('open_id_type', 23, 'string'));
  LoginReq.add(new protobuf.Field('login_token', 29, 'string'));
  LoginReq.add(new protobuf.Field('orign_platform_type', 99, 'string'));
  FreeFire.add(LoginReq);
  const LoginRes = new protobuf.Type('LoginRes');
  LoginRes.add(new protobuf.Field('account_id', 1, 'uint64'));
  LoginRes.add(new protobuf.Field('lock_region', 2, 'string'));
  LoginRes.add(new protobuf.Field('noti_region', 3, 'string'));
  LoginRes.add(new protobuf.Field('ip_region', 4, 'string'));
  LoginRes.add(new protobuf.Field('agora_environment', 5, 'string'));
  LoginRes.add(new protobuf.Field('new_active_region', 6, 'string'));
  LoginRes.add(new protobuf.Field('recommend_regions', 7, 'string', 'repeated'));
  LoginRes.add(new protobuf.Field('token', 8, 'string'));
  LoginRes.add(new protobuf.Field('ttl', 9, 'uint32'));
  LoginRes.add(new protobuf.Field('server_url', 10, 'string'));
  LoginRes.add(new protobuf.Field('emulator_score', 11, 'uint32'));
  LoginRes.add(new protobuf.Field('tp_url', 14, 'string'));
  LoginRes.add(new protobuf.Field('app_server_id', 15, 'uint32'));
  LoginRes.add(new protobuf.Field('ano_url', 16, 'string'));
  LoginRes.add(new protobuf.Field('ip_city', 17, 'string'));
  LoginRes.add(new protobuf.Field('ip_subdivision', 18, 'string'));
  FreeFire.add(LoginRes);
  root.add(FreeFire);
  const main = new protobuf.Namespace('main');
  const GetPlayerPersonalShow = new protobuf.Type('GetPlayerPersonalShow');
  GetPlayerPersonalShow.add(new protobuf.Field('a', 1, 'int64'));
  GetPlayerPersonalShow.add(new protobuf.Field('b', 2, 'int32'));
  main.add(GetPlayerPersonalShow);
  root.add(main);
  const freefire = new protobuf.Namespace('freefire');
  const AccountInfoBasic = new protobuf.Type('AccountInfoBasic');
  AccountInfoBasic.add(new protobuf.Field('account_id', 1, 'uint64', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('account_type', 2, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('nickname', 3, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('external_id', 4, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('region', 5, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('level', 6, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('exp', 7, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('external_type', 8, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('external_name', 9, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('external_icon', 10, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('banner_id', 11, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('head_pic', 12, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('clan_name', 13, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('rank', 14, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('ranking_points', 15, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('role', 16, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('has_elite_pass', 17, 'bool', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('badge_cnt', 18, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('badge_id', 19, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('season_id', 20, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('liked', 21, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('is_deleted', 22, 'bool', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('show_rank', 23, 'bool', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('last_login_at', 24, 'int64', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('external_uid', 25, 'uint64', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('return_at', 26, 'int64', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('championship_team_name', 27, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('championship_team_member_num', 28, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('championship_team_id', 29, 'uint64', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('cs_rank', 30, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('cs_ranking_points', 31, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('weapon_skin_shows', 32, 'uint32', 'repeated'));
  AccountInfoBasic.add(new protobuf.Field('pin_id', 33, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('is_cs_ranking_ban', 34, 'bool', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('max_rank', 35, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('cs_max_rank', 36, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('max_ranking_points', 37, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('game_bag_show', 38, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('peak_rank_pos', 39, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('cs_peak_rank_pos', 40, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('periodic_ranking_points', 42, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('periodic_rank', 43, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('create_at', 44, 'int64', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('selected_item_slots', 46, 'uint32', 'repeated'));
  AccountInfoBasic.add(new protobuf.Field('title', 48, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('release_version', 50, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('veteran_expire_time', 51, 'uint64', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('show_br_rank', 52, 'bool', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('show_cs_rank', 53, 'bool', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('clan_id', 54, 'uint64', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('clan_badge_id', 55, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('custom_clan_badge', 56, 'string', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('use_custom_clan_badge', 57, 'bool', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('clan_frame_id', 58, 'uint32', 'optional'));
  AccountInfoBasic.add(new protobuf.Field('membership_state', 59, 'bool', 'optional'));
  freefire.add(AccountInfoBasic);
  const AvatarProfile = new protobuf.Type('AvatarProfile');
  AvatarProfile.add(new protobuf.Field('avatar_id', 1, 'uint32', 'optional'));
  AvatarProfile.add(new protobuf.Field('skin_color', 3, 'uint32', 'optional'));
  AvatarProfile.add(new protobuf.Field('clothes', 4, 'uint32', 'repeated'));
  AvatarProfile.add(new protobuf.Field('equiped_skills', 5, 'uint32', 'repeated'));
  AvatarProfile.add(new protobuf.Field('is_selected', 6, 'bool', 'optional'));
  AvatarProfile.add(new protobuf.Field('pve_primary_weapon', 7, 'uint32', 'optional'));
  AvatarProfile.add(new protobuf.Field('is_selected_awaken', 8, 'bool', 'optional'));
  AvatarProfile.add(new protobuf.Field('end_time', 9, 'uint32', 'optional'));
  AvatarProfile.add(new protobuf.Field('unlock_type', 10, 'int32', 'optional')); 
  AvatarProfile.add(new protobuf.Field('unlock_time', 11, 'uint32', 'optional'));
  AvatarProfile.add(new protobuf.Field('is_marked_star', 12, 'bool', 'optional'));
  AvatarProfile.add(new protobuf.Field('clothes_tailor_effects', 13, 'uint32', 'repeated'));
  freefire.add(AvatarProfile);
  const AccountNewsContent = new protobuf.Type('AccountNewsContent');
  AccountNewsContent.add(new protobuf.Field('item_ids', 1, 'uint32', 'repeated'));
  AccountNewsContent.add(new protobuf.Field('rank', 2, 'uint32', 'optional'));
  AccountNewsContent.add(new protobuf.Field('match_mode', 3, 'uint32', 'optional'));
  AccountNewsContent.add(new protobuf.Field('map_id', 4, 'uint32', 'optional'));
  AccountNewsContent.add(new protobuf.Field('game_mode', 5, 'uint32', 'optional'));
  AccountNewsContent.add(new protobuf.Field('group_mode', 6, 'uint32', 'optional'));
  AccountNewsContent.add(new protobuf.Field('treasurebox_id', 7, 'uint32', 'optional'));
  AccountNewsContent.add(new protobuf.Field('commodity_id', 8, 'uint32', 'optional'));
  AccountNewsContent.add(new protobuf.Field('store_id', 9, 'uint32', 'optional'));
  freefire.add(AccountNewsContent);
  const AccountNews = new protobuf.Type('AccountNews');
  AccountNews.add(new protobuf.Field('type', 1, 'int32', 'optional')); 
  AccountNews.add(new protobuf.Field('content', 2, 'freefire.AccountNewsContent', 'optional'));
  AccountNews.add(new protobuf.Field('update_time', 3, 'int64', 'optional'));
  freefire.add(AccountNews);
  const BasicEPInfo = new protobuf.Type('BasicEPInfo');
  BasicEPInfo.add(new protobuf.Field('ep_event_id', 1, 'uint32', 'optional'));
  BasicEPInfo.add(new protobuf.Field('owned_pass', 2, 'bool', 'optional'));
  BasicEPInfo.add(new protobuf.Field('ep_badge', 3, 'uint32', 'optional'));
  BasicEPInfo.add(new protobuf.Field('badge_cnt', 4, 'uint32', 'optional'));
  BasicEPInfo.add(new protobuf.Field('bp_icon', 5, 'string', 'optional'));
  BasicEPInfo.add(new protobuf.Field('max_level', 6, 'uint32', 'optional'));
  BasicEPInfo.add(new protobuf.Field('event_name', 7, 'string', 'optional'));
  freefire.add(BasicEPInfo);
  const ClanInfoBasic = new protobuf.Type('ClanInfoBasic');
  ClanInfoBasic.add(new protobuf.Field('clan_id', 1, 'uint64', 'optional'));
  ClanInfoBasic.add(new protobuf.Field('clan_name', 2, 'string', 'optional'));
  ClanInfoBasic.add(new protobuf.Field('captain_id', 3, 'uint64', 'optional'));
  ClanInfoBasic.add(new protobuf.Field('clan_level', 4, 'uint32', 'optional'));
  ClanInfoBasic.add(new protobuf.Field('capacity', 5, 'uint32', 'optional'));
  ClanInfoBasic.add(new protobuf.Field('member_num', 6, 'uint32', 'optional'));
  ClanInfoBasic.add(new protobuf.Field('honor_point', 7, 'uint32', 'optional'));
  freefire.add(ClanInfoBasic);
  const PetSkillInfo = new protobuf.Type('PetSkillInfo');
  PetSkillInfo.add(new protobuf.Field('pet_id', 1, 'uint32', 'optional'));
  PetSkillInfo.add(new protobuf.Field('skill_id', 2, 'uint32', 'optional'));
  PetSkillInfo.add(new protobuf.Field('skill_level', 3, 'uint32', 'optional'));
  freefire.add(PetSkillInfo);
  const PetInfo = new protobuf.Type('PetInfo');
  PetInfo.add(new protobuf.Field('id', 1, 'uint32', 'optional'));
  PetInfo.add(new protobuf.Field('name', 2, 'string', 'optional'));
  PetInfo.add(new protobuf.Field('level', 3, 'uint32', 'optional'));
  PetInfo.add(new protobuf.Field('exp', 4, 'uint32', 'optional'));
  PetInfo.add(new protobuf.Field('is_selected', 5, 'bool', 'optional'));
  PetInfo.add(new protobuf.Field('skin_id', 6, 'uint32', 'optional'));
  PetInfo.add(new protobuf.Field('actions', 7, 'uint32', 'repeated'));
  PetInfo.add(new protobuf.Field('skills', 8, 'freefire.PetSkillInfo', 'repeated'));
  PetInfo.add(new protobuf.Field('selected_skill_id', 9, 'uint32', 'optional'));
  PetInfo.add(new protobuf.Field('is_marked_star', 10, 'bool', 'optional'));
  PetInfo.add(new protobuf.Field('end_time', 11, 'uint32', 'optional'));
  freefire.add(PetInfo);
  const SocialBasicInfo = new protobuf.Type('SocialBasicInfo');
  SocialBasicInfo.add(new protobuf.Field('account_id', 1, 'uint64', 'optional'));
  SocialBasicInfo.add(new protobuf.Field('gender', 2, 'int32', 'optional')); 
  SocialBasicInfo.add(new protobuf.Field('language', 3, 'int32', 'optional')); 
  SocialBasicInfo.add(new protobuf.Field('time_online', 4, 'int32', 'optional')); 
  SocialBasicInfo.add(new protobuf.Field('time_active', 5, 'int32', 'optional')); 
  SocialBasicInfo.add(new protobuf.Field('battle_tag', 6, 'int32', 'repeated')); 
  SocialBasicInfo.add(new protobuf.Field('social_tag', 7, 'int32', 'repeated')); 
  SocialBasicInfo.add(new protobuf.Field('mode_prefer', 8, 'int32', 'optional')); 
  SocialBasicInfo.add(new protobuf.Field('signature', 9, 'string', 'optional'));
  SocialBasicInfo.add(new protobuf.Field('rank_show', 10, 'int32', 'optional')); 
  SocialBasicInfo.add(new protobuf.Field('battle_tag_count', 11, 'uint32', 'repeated'));
  SocialBasicInfo.add(new protobuf.Field('signature_ban_expire_time', 12, 'int64', 'optional'));
  freefire.add(SocialBasicInfo);
  const DiamondCostRes = new protobuf.Type('DiamondCostRes');
  DiamondCostRes.add(new protobuf.Field('diamond_cost', 1, 'uint32', 'optional'));
  freefire.add(DiamondCostRes);
  const CreditScoreInfoBasic = new protobuf.Type('CreditScoreInfoBasic');
  CreditScoreInfoBasic.add(new protobuf.Field('credit_score', 1, 'uint32', 'optional'));
  CreditScoreInfoBasic.add(new protobuf.Field('is_init', 2, 'bool', 'optional'));
  CreditScoreInfoBasic.add(new protobuf.Field('reward_state', 3, 'int32', 'optional')); 
  CreditScoreInfoBasic.add(new protobuf.Field('periodic_summary_like_cnt', 4, 'uint32', 'optional'));
  CreditScoreInfoBasic.add(new protobuf.Field('periodic_summary_illegal_cnt', 5, 'uint32', 'optional'));
  CreditScoreInfoBasic.add(new protobuf.Field('weekly_match_cnt', 6, 'uint32', 'optional'));
  CreditScoreInfoBasic.add(new protobuf.Field('periodic_summary_start_time', 7, 'int64', 'optional'));
  CreditScoreInfoBasic.add(new protobuf.Field('periodic_summary_end_time', 8, 'int64', 'optional'));
  freefire.add(CreditScoreInfoBasic);
  const EquipAchInfo = new protobuf.Type('EquipAchInfo');
  EquipAchInfo.add(new protobuf.Field('ach_id', 1, 'uint32', 'optional'));
  EquipAchInfo.add(new protobuf.Field('level', 2, 'uint32', 'optional'));
  freefire.add(EquipAchInfo);
  const AccountPersonalShowInfo = new protobuf.Type('AccountPersonalShowInfo');
  AccountPersonalShowInfo.add(new protobuf.Field('basic_info', 1, 'freefire.AccountInfoBasic', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('profile_info', 2, 'freefire.AvatarProfile', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('ranking_leaderboard_pos', 3, 'int32', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('news', 4, 'freefire.AccountNews', 'repeated'));
  AccountPersonalShowInfo.add(new protobuf.Field('history_ep_info', 5, 'freefire.BasicEPInfo', 'repeated'));
  AccountPersonalShowInfo.add(new protobuf.Field('clan_basic_info', 6, 'freefire.ClanInfoBasic', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('captain_basic_info', 7, 'freefire.AccountInfoBasic', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('pet_info', 8, 'freefire.PetInfo', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('social_info', 9, 'freefire.SocialBasicInfo', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('diamond_cost_res', 10, 'freefire.DiamondCostRes', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('credit_score_info', 11, 'freefire.CreditScoreInfoBasic', 'optional'));
  AccountPersonalShowInfo.add(new protobuf.Field('pre_veteran_type', 12, 'int32', 'optional')); 
  AccountPersonalShowInfo.add(new protobuf.Field('equipped_ach', 13, 'freefire.EquipAchInfo', 'repeated'));
  AccountPersonalShowInfo.add(new protobuf.Field('unknown_field_15', 15, 'bytes', 'optional'));
  freefire.add(AccountPersonalShowInfo);
  root.add(freefire);
  return root;
}
